132 sharing profile
Rigtch/rigtch-fm-www pull request #164
Opened 2023-12-22 13:20 UTC by Mnigos

closes #132

2023-12-23 13:54 UTC, Iqro-dev commented on app/api/constants/errors.ts
> +  'Validation failed (uuid is expected)'
```suggestion
  'Validation failed (uuid expected)'
```

2024-01-15 18:54 UTC, Iqro-dev requested changes

2024-01-15 18:54 UTC, Iqro-dev commented on middleware.spec.ts
> +  test('should return if no cokies', async () => {
add double 'o'

2024-01-15 18:56 UTC, Mnigos commented on app/profile/[user-id]/not-found.tsx
> +        <h2>Not Found</h2>
That will be your task to create pretty Not Found page

2024-01-15 18:59 UTC, Iqro-dev approved these changes

2024-01-15 19:02 UTC, merged