feat(home): add cookies dialog
Rigtch/rigtch-fm-www pull request #192
Opened 2024-01-18 14:31 UTC by Iqro-dev

closes #188

2024-01-18 20:17 UTC, Mnigos requested changes

2024-01-18 20:17 UTC, Mnigos commented on app/hooks/use-auth-cookies.tsx
> +    userAcceptCookies: cookie[USER_ACCEPT_COOKIES] as boolean,
This is not auth cookie. just use `useCookies` hook in dialog component

2024-01-25 08:59 UTC, Mnigos commented
This popup should appear on all pages not only on home. User shouldn't be able to access his profile without accepting cookies policy.

2024-01-26 10:17 UTC, Mnigos approved these changes

2024-01-26 10:17 UTC, Mnigos commented on app/cookies-dialog.tsx
> +'use client'
```suggestion
'use client'

```

2024-01-26 10:17 UTC, Mnigos commented on app/layout.tsx
> +  const isAccepted = cookies().has(USER_ACCEPT_COOKIES as string)
why `as string`?

2024-01-26 11:21 UTC, Iqro-dev commented on app/layout.tsx
> +  const isAccepted = cookies().has(USER_ACCEPT_COOKIES as string)
because it throws an error "unsafe assignment of any"

2024-01-26 11:59 UTC, merged